version: 0.2

proxy:
  upload-artifacts: yes
  logs: yes
  
phases:
  install:
    runtime-version: 
      node.js: 12
      python: 3.8
  
  pre_build: 
    commands:
      - env
      - mkdir test
      - cd test
      - echo "TESTING"
     
  build:
    commands:
      - ls -la
      - git submodule init
      - echo $CODEBUILD_SOURCE_VERSION
      
  post_build: 
    commands: 
      - echo "build completed on 'date'"
      - git log --name-only
      - git diff --name-only $GIT_PREVIOUS_COMMIT $GIT_COMMIT
